export const fieldConfig = [
    {
      id: 'category',
      label: 'Category',
      type: 'select',
      options: [
        { value: 9, label: 'General Knowledge' },
        { value: 10, label: 'Books' },
        { value: 11, label: 'Films' },
        { value: 12, label: 'Music' },
        { value: 13, label: 'Musicals and Theaters' },
        { value: 14, label: 'Television' },
        { value: 15, label: 'Video Games' },
        { value: 16, label: 'Board Games' },
        { value: 17, label: 'Science and Nature' },
        { value: 18, label: 'Computer' },
        { value: 19, label: 'Mathematics' },
        { value: 20, label: 'Mythology' },
        { value: 21, label: "Sports" },
        { value: 22, label: 'Geography' },
        { value: 23, label: 'History' },
        { value: 24, label: 'Politics' },
        { value: 25, label: 'Art' },
        { value: 26, label: 'Celebrities' },
        { value: 27, label: 'Animals' },
        { value: 28, label: 'Vehicles' },
        { value: 29, label: 'Comics' },
        { value: 30, label: 'Gadgets' },
        { value: 31, label: 'Japanese Anime' },
        { value: 32, label: 'Cartoon and Animals' },
      ],
    },
    {
      id: 'difficulty',
      label: 'Difficulty',
      type: 'select',
      options: [
        { value: 'easy', label: 'Easy' },
        { value: 'medium', label: 'Medium' },
        { value: 'hard', label: 'Hard' },
      ],
    },
    {
      id: 'type',
      label: 'Type',
      type: 'select',
      options: [
        { value: 'multiple', label: 'Multiple Choice' },
        { value: 'boolean', label: 'True/False' },
      ],
    },
    {
      id: 'numberOfQuestions',
      label: 'Number of Questions',
      type: 'select',
      options: [
        { value: 5, label: '5' },
        { value: 10, label: '10' },
        { value: 15, label: '15' },
      ], 
    },
    {
      id: 'timer',
      label: 'Timer',
      type: 'select',
      options: [
        { value: 60, label: '1 Minute' },
        { value: 120, label: '2 Minutes' },
        { value: 300, label: '5 Minutes' },
      ],
    },
  ];